name: Daily Ticker Refresh

on:
  schedule:
    - cron: '0 8 * * *' #8AM UTC -> 4AM EST
  workflow_dispatch:

jobs:
  run-update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system curl-impersonate deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev pkg-config build-essential

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ticker update file
        run: python update_tickers.py

      - name: Get date
        env:
          TZ: America/New_York
        run: echo "DATE=$(date +"%Y-%m-%d %H:%M:%S %Z")" >> $GITHUB_ENV #sets variable DATE in $GITHUB_ENV, accessible with prefix env. %Z is the timezone shortcut

      - name: Commit and push updated file
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          message: "Ticker list updated on ${{ env.DATE }}"
